### PR TITLE
Add Travis CI to test and deploy

### PR DESCRIPTION
**Pull request by SkypLabs**
Hello,

This pull request aims to use Travis CI to test that the code successfully builds and to attach the resulting JAR file to the related GitHub release note (see an example [here][release note example]).

The current `.travis.yml` will:

* Build the project using the two following JDKs:
    * OpenJDK 8
    * Oracle JDK 8
* If all the build jobs have succeeded, attach the JAR file to the related GitHub release note (only for git tags)

Before accepting this pull request, you need to:

* Add [Travis CI][add travis ci] to your GitHub account
* Replace the value of `secure` with your own encrypted token:
    * Go to https://github.com/settings/tokens
    * Click on `Generate new token`
    * Check only `public_repo` in the list
    * Encrypt the token using [Travis CLI][encrypt data]

 [add travis ci]: https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI
 [encrypt data]: https://docs.travis-ci.com/user/encryption-keys/#Usage
 [release note example]: https://github.com/SkypLabs/hypergraphql/releases/tag/release-test

### CODE REVIEW

**Comment by pc3356** [comment]
Hello,

Which ticket does this address? Please can you introduce yourself and provide some credentials, along with some context of why you want to add this behaviour?

Many thanks,

**Comment by SkypLabs** [comment]
Since when do we have to introduce ourself to participate in open-source projects?

Regarding the reason of this pull request, I thought it was obvious. As described in the description I wrote, it is a way to be sure that the project compiles well when releasing a new version, avoiding #19 for example. In addition, publishing the JAR file allows to deploy the server without the need to compile it (and to set up a development environment so).

**Comment by pc3356** [comment]
Hello,

First of all, thanks very much for taking the time to contribute, we do value this greatly.

We do need to manage contributions and ensure they align with roadmaps and existing development efforts, including, in this case managing builds for Java 8, 9 and 10+

It's not unusual for contributors to make themselves and their pedigree/interests known to an open source project, and you raise an interesting issue that we should publish some contribution guidelines. 

Can I request at the very least that you raise a ticket for this so we can connect the pull request to it, and explain the details of why this is required - remember that 'obvious' is a subjective term.

Many thanks,

**Comment by SkypLabs** [comment]
> First of all, thanks very much for taking the time to contribute, we do value this greatly.

Sorry if my last message was a bit curt but I have to admit that I was really surprised and disappointed when I saw your answer, specially when you talked about "credentials". It is not a way to welcome contributors and to get people involved in an open-source project.

> We do need to manage contributions and ensure they align with roadmaps and existing development efforts, including, in this case managing builds for Java 8, 9 and 10+

I understand but it is not necessary to merge a pull request straight away. Thanks to Git's branching model, we can simple talk about the best way to implement my contribution here if you think it is valuable and merge it when it is appropriate. I am used to open pull requests for a lot of open-source projects and to see them merged months later.

Also, I haven't seen any public roadmaps for this project. An easy way to make it public is to use the ["project"](https://github.com/semantic-integration/hypergraphql/projects) feature of GitHub (just a suggestion).

> It's not unusual for contributors to make themselves and their pedigree/interests known to an open source project, and you raise an interesting issue that we should publish some contribution guidelines.

Yes, publishing some contribution guidelines is a great idea :+1: 

> Can I request at the very least that you raise a ticket for this so we can connect the pull request to it, and explain the details of why this is required - remember that 'obvious' is a subjective term.

Of course, I will.

Thanks,

**Pull request merged**
